version: '3.8'

services:
  # O Banco de Dados Principal
  db:
    image: postgres:15-alpine
    container_name: justgo_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - justgo-network

  # O Backend (API)
  backend:
    build: ./backend-core
    container_name: justgo_core
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend-core:/app
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
    depends_on:
      - db
    networks:
      - justgo-network

volumes:
  postgres_data:

networks:
  justgo-network:
    driver: bridge
